name: 'Publish, deploy and run Docker image'
on:
  workflow_dispatch:
    inputs:
      DEBUG_FLAG:
        description: '0 to Enable write db, 1 to disable write db'
        required: true
      NUM_OF_REQUEST:
        description: 'numbers of requests, default is -1 means send all data in database'
        required: false
        default: '-1'
      SKIP_PUBLISH_DOCKER_IMAGE:
        description: 'whether to skip building and publishing new docker image'
        required: false
        default: 'false'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.event.inputs.SKIP_PUBLISH_DOCKER_IMAGE != 'true'
        with:
          name: highperformancecomputing/cte
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest

      #      - name: Start database
      #        uses: dawidd6/action-ansible-playbook@v2
      #        with:
      #          playbook: start_database.yml
      #          directory: ./deployment/ansible_playbook
      - name: Stop clusrer
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: stop_cluster.yml
          directory: ./deployment/ansible_playbook

      - name: Start cte match engin
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_cte_match_engine.yml
          directory: ./deployment/ansible_playbook

      - name: Start akka_te match engin
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_akka_te_match_engine.yml
          directory: ./deployment/ansible_playbook

      - name: Start akka_te sub match engin
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_akka_te_sub_match_engine.yml
          directory: ./deployment/ansible_playbook

      - name: Start cte sub match engin
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_cte_sub_match_engine.yml
          directory: ./deployment/ansible_playbook

      - name: Start trade manager
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_trade_manager.yml
          directory: ./deployment/ansible_playbook

      - name: Start cte order manager
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_cte_order_manager.yml
          directory: ./deployment/ansible_playbook
          options: |
            --extra-vars DEBUG=${{ github.event.inputs.DEBUG_FLAG }}
      - name: Start akka order manager
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_akka_order_manager.yml
          directory: ./deployment/ansible_playbook
          options: |
            --extra-vars DEBUG=${{ github.event.inputs.DEBUG_FLAG }}
      - name: Start request generator
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start_cte_request_generator.yml
          directory: ./deployment/ansible_playbook
          options: |
            --extra-vars NUM_OF_REQUEST=${{ github.event.inputs.NUM_OF_REQUEST }}